version: "3"

services:
  database:
    image: mysql
    container_name: mysql-deploy-study
    environment:
      - MYSQL_DATABASE=deploy_challenge
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=5205
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/database/mysql/:/var/lib/mysql

  application:
    build: .
    restart: always

